name: Build Single Popular App
on:
  push:
    branches:
      - 'main'
    # paths:
    #   - '**/builder.yml'

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # - platform: 'macos-latest' # for Arm based macs (M1 and above).
          #   args: '--target aarch64-apple-darwin'
          # - platform: 'macos-latest' # for Intel based macs.
          #   args: '--target x86_64-apple-darwin'
          # - platform: 'ubuntu-latest'
          #   args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev gnome-video-effects gnome-video-effects-extra
          version: 1.1

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: install frontend dependencies
        run: |
          pnpm i

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

      # - name: Config App
      #   env:
      #     NAME: ${{ inputs.name }}
      #     TITLE: ${{ inputs.title }}
      #     NAME_ZH: ${{ inputs.name_zh }}
      #     URL: ${{ inputs.url }}
      #   run: |
      #     npm install
      #     npm run build:config

      # - name: Build for Ubuntu
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     npm run tauri build
      #     mkdir -p output/linux
      #     mv src-tauri/target/release/bundle/deb/*.deb output/linux/${{inputs.title}}_`arch`.deb
      #     mv src-tauri/target/release/bundle/appimage/*.AppImage output/linux/"${{inputs.title}}"_`arch`.AppImage

      # - name: Build for macOS
      #   if: matrix.os == 'macos-latest'
      #   run: |
      #     rustup target add aarch64-apple-darwin
      #     rustup target add x86_64-apple-darwin
      #     npm run tauri build -- --target universal-apple-darwin
      #     mkdir -p output/macos
      #     mv src-tauri/target/universal-apple-darwin/release/bundle/dmg/*.dmg output/macos/"${{inputs.title}}".dmg

      # - name: Build for Windows
      #   if: matrix.os == 'windows-latest'
      #   run: |
      #     pnpm run tauri build


      # - uses: actions/upload-artifact@v4
      #   name: Upload the artifact
      #   with:
      #     name: bundle
      #     path: src-tauri\target\release\bundle

          
      # - name: Restore Cargo Lock File(Windows Only)
      #   if: matrix.os == 'windows-latest'
      #   run: |
      #     git checkout -- src-tauri/Cargo.lock

      # - name: Rust cache store
      #   uses: actions/cache/save@v3
      #   with:
      #     path: |
      #       ~/.cargo/bin/
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #       src-tauri/target/
      #     key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # - name: Upload For Single Build
      #   uses: actions/upload-artifact@v3
      #   if: startsWith(github.ref, 'refs/tags/') != true
      #   with:
      #     path: 'output/*/*.*'

      # - name: Upload For Release
      #   # arg info: https://github.com/ncipollo/release-action#release-action
      #   uses: ncipollo/release-action@v1
      #   if: startsWith(github.ref, 'refs/tags/') == true
      #   with:
      #     allowUpdates: true
      #     artifacts: 'output/*/*.*'
      #     token: ${{ secrets.GITHUB_TOKEN }}